### ISSUE TITLE
旅游照片，有问题，，

### ISSUE THREAD

**Issue by SuperKenVery** [USTC-Hackergame/hackergame2022-writeups#14]
macOS里写的exif版本是2.3.1，多了一个点……

到底哪个才是对的呢

**Comment by Lasius-alienus** [comment]
windows显示0231，应该只是版本号表示方式不同，实际代表的都是一个版本

**Comment by SmartHypercube** [comment]
这和 macOS/Windows 操作系统无关，取决于显示这个信息的软件是否正确解析和显示了文件中 EXIF 信息。EXIF 信息的正确解析方式要以 EXIF 规范中的定义为准。0231 应该是比较接近底层实际存储的形式，实际表示 2.31 这个版本。由于 EXIF 最近几个版本的编号分别是 2.0 2.1 2.2 2.21 2.3 2.31 2.32，可以看出“31”其实语义上更像是 3.1，显示为 2.3.1 也可以理解。但无论是 0231 还是 2.3.1 都不是真正准确的版本号。
