### ISSUE TITLE
Better solution for "LaTeX 机器人"

### ISSUE THREAD

**Issue by tiankaima** [USTC-Hackergame/hackergame2022-writeups#37]
Try this:
```latex
$$
\begingroup
\catcode `\$=12
\catcode `\#=12
\catcode `\_=12
\catcode `\&=12
\input{/flag2}
\endgroup
$$
```

Really not worth making a PR for this...

ref: https://github.com/USTC-Hackergame/hackergame2022-writeups/blob/master/official/LaTeX%20%E6%9C%BA%E5%99%A8%E4%BA%BA/README.md

**Comment by nidwbin** [comment]
My solution is very similar to yours.
```
$$\catcode `\_=12 \catcode`\#=12 \input{/flag2}$$
```
\catcode \`\\&=12 and \catcode \`\\$=12 is useless in this question. So I didn't redefine them.XD.
There is more information about catcode(category code) in this [link(Chinese)](https://liam.page/2018/05/05/TeX-by-Topic-Category-Codes-and-Internal-States/).

**Comment by tiankaima** [comment]
> My solution is very similar to yours.
> 
> ```
> $$\catcode `\_=12 \catcode`\#=12 \input{/flag2}$$
> ```
> 
> \catcode `\&=12 and \catcode `\$=12 is useless in this question. So I didn't redefine them.XD. There is more information about catcode(category code) in this [link(Chinese)](https://liam.page/2018/05/05/TeX-by-Topic-Category-Codes-and-Internal-States/).

I was just browsing StackOverFlow and found this solution... Didn't really dig into `\catcode` LOL, thanks for the link though.

The original method I tried was similar to [this](https://github.com/USTC-Hackergame/hackergame2022-writeups/blob/master/players/mcfx/wp.md#latex-%E6%9C%BA%E5%99%A8%E4%BA%BA) but copying the `.sty` file never worked for me for some reason.

Then there were tons of tries to break the `\write18` limit, which I did succeed and got the flag, but I believe it was a stupid bug in `pdflatex` and probably an unintended solution. I still don't have any replies, so after digging a bit a came across that question on StackOverflow ... 

Also worth mentioning is that if `/flag2` contains characters `\`  `{` or `}`, this solution isn't going to work (the `\input` command is going to be printed out, that way is probably going to require a `\def` alongside `\group`, worth trying and perhaps will well worth become a question in other CTF contests (for example getting shell from a remote host).

`LaTeX` has always been this troublesome yet somewhat fun thing to learn ... probably something that will continue to confuse and bother me in the following years. Thanks again for the link, real inspiring.

> Modify:
> I just found that the given `/flag2` does contain `{` and `}` , but I never got it running on my local env (MiKTeX) and WSL env (pdfLaTeX). This is really strange though, but I really don't spare time now figuring this out, maybe later this week and I'll repost a reply further on this 😄

**Comment by nidwbin** [comment]
> > My solution is very similar to yours.
> > ```
> > $$\catcode `\_=12 \catcode`\#=12 \input{/flag2}$$
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > \catcode `\&=12 and \catcode `$=12 is useless in this question. So I didn't redefine them.XD. There is more information about catcode(category code) in this [link(Chinese)](https://liam.page/2018/05/05/TeX-by-Topic-Category-Codes-and-Internal-States/).
> 
> I was just browsing StackOverFlow and found this solution... Didn't really dig into `\catcode` LOL, thanks for the link though.
> 
> The original method I tried was similar to [this](https://github.com/USTC-Hackergame/hackergame2022-writeups/blob/master/players/mcfx/wp.md#latex-%E6%9C%BA%E5%99%A8%E4%BA%BA) but copying the `.sty` file never worked for me for some reason.
> 
> Then there were tons of tries to break the `\write18` limit, which I did succeed and got the flag, but I believe it was a stupid bug in `pdflatex` and probably an unintended solution. I still don't have any replies, so after digging a bit a came across that question on StackOverflow ...
> 
> Also worth mentioning is that if `/flag2` contains characters `\` `{` or `}`, this solution isn't going to work (the `\input` command is going to be printed out, that way is probably going to require a `\def` alongside `\group`, worth trying and perhaps will well worth become a question in other CTF contests (for example getting shell from a remote host).
> 
> `LaTeX` has always been this troublesome yet somewhat fun thing to learn ... probably something that will continue to confuse and bother me in the following years. Thanks again for the link, real inspiring.
> 
> > Modify:
> > I just found that the given `/flag2` does contain `{` and `}` , but I never got it running on my local env (MiKTeX) and WSL env (pdfLaTeX). This is really strange though, but I really don't spare time now figuring this out, maybe later this week and I'll repost a reply further on this 😄

Acturally, I just found the best version is
```
$$\catcode `\_=13 \catcode `\#=12 \input{/flag2}$$
```
`_` is showed as `_` rather than `.`.
If `/flag2` contains more `{` and `}` in the content, I think there maybe no answer because of `{` and `}` in command `\input{}` and other commands in the context of latex file. 
I means if you want to print `{` and `}` in flag, you need to redefine two new characters (such as `(` and `)`) to replace `{`and`}`.
But we can not change `{`  and `}` in the rest of latex file. So, there maybe no answer (just maybe XD).
