### ISSUE TITLE
HeiLang 的 Write-Up 未更新附件所在路径

### ISSUE THREAD

**Issue by wuhang2003** [USTC-Hackergame/hackergame2022-writeups#61]
https://github.com/USTC-Hackergame/hackergame2022-writeups/blob/ba513b59c6b460f4bdab4ccae84cd7f0f4bc1b02/official/HeiLang/README.md?plain=1#L19

应为 `src/getflag.hei.py`
~~不好意思单独为这个问题开 PR，所以提 issues 了~~

**Comment by taoky** [comment]
Fixed in 77f8121c3c7a9b9d948a4343d2ac736556d81a1b
